### ISSUE TITLE
Breaks: AttributeError: 'NoneType' object has no attribute 'match_view'

### ISSUE THREAD

**Issue by reagle** [STealthy-and-haSTy/EnhancedSnippets#9]
Perhaps this is related to what we discussed on discord, but ES no longer works for me and throws an exception. I'm not sure what would've changed other than using alpha1 package.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1077, in on_query_completions
    norm_res(callback(v, prefix, locations))
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "/Users/reagle/Library/Application Support/Sublime Text/Installed Packages/EnhancedSnippets.sublime-package/src/events.py", line 122, in on_query_completions
    snippets = SnippetManager.instance.match_view(view, locations)
AttributeError: 'NoneType' object has no attribute 'match_view'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1077, in on_query_completions
    norm_res(callback(v, prefix, locations))
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "/Users/reagle/Library/Application Support/Sublime Text/Installed Packages/EnhancedSnippets.sublime-package/src/events.py", line 122, in on_query_completions
    snippets = SnippetManager.instance.match_view(view, locations)
AttributeError: 'NoneType' object has no attribute 'match_view'
```

**Comment by reagle** [comment]
I restarted ST4 and ES is working again...
